// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class BuildingResearchManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.BuildingResearch>;

	function get_query() : orm.SqlQuery<com.lak.models.BuildingResearch>
	{
		return new orm.SqlQuery<com.lak.models.BuildingResearch>("building_research", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_building:Int, id_research:Int, finish:Int) : com.lak.models.BuildingResearch
	{
		var _obj = new com.lak.models.BuildingResearch(db, orm);
		_obj.id = id;
		_obj.id_building = id_building;
		_obj.id_research = id_research;
		_obj.finish = finish;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.BuildingResearch
	{
		var _obj = new com.lak.models.BuildingResearch(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_building = Reflect.field(d, 'id_building');
		_obj.id_research = Reflect.field(d, 'id_research');
		_obj.finish = Reflect.field(d, 'finish');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.BuildingResearch>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.BuildingResearch
	{
		return getBySqlOne('SELECT * FROM `building_research` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, id_building:Int, id_research:Int, finish:Int) : com.lak.models.BuildingResearch
	{
		db.query('INSERT INTO `building_research`(`id`, `id_building`, `id_research`, `finish`) VALUES (' + db.quote(id) + ', ' + db.quote(id_building) + ', ' + db.quote(id_research) + ', ' + db.quote(finish) + ')');
		return newModelFromParams(id, id_building, id_research, finish);
	}

	public function createNamed(data:{ id:Int, id_building:Int, id_research:Int, finish:Int }) : com.lak.models.BuildingResearch
	{
		db.query('INSERT INTO `building_research`(`id`, `id_building`, `id_research`, `finish`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.id_building) + ', ' + db.quote(data.id_research) + ', ' + db.quote(data.finish) + ')');
		return newModelFromParams(data.id, data.id_building, data.id_research, data.finish);
	}

	public function createOptional(data:{ id:Int, ?id_building:Int, ?id_research:Int, ?finish:Int }) : com.lak.models.BuildingResearch
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?id_building:Int, ?id_research:Int, ?finish:Int }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'id_building')) { fields.push('`id_building`'); values.push(db.quote(data.id_building)); }
		if (Reflect.hasField(data, 'id_research')) { fields.push('`id_research`'); values.push(db.quote(data.id_research)); }
		if (Reflect.hasField(data, 'finish')) { fields.push('`finish`'); values.push(db.quote(data.finish)); }
		db.query('INSERT INTO `building_research`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `building_research` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.BuildingResearch>
	{
		return getBySqlMany('SELECT * FROM `building_research`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.BuildingResearch
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.BuildingResearch>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.BuildingResearch> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_building(id_building:Int, _order:String=null) : Array<com.lak.models.BuildingResearch>
	{
		return getBySqlMany('SELECT * FROM `building_research` WHERE `id_building` = ' + db.quote(id_building) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_research(id_research:Int, _order:String=null) : Array<com.lak.models.BuildingResearch>
	{
		return getBySqlMany('SELECT * FROM `building_research` WHERE `id_research` = ' + db.quote(id_research) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}