// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class BuildingResearch
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_building : Int;
	public var id_research : Int;
	public var finish : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_building:Int, id_research:Int, finish:Int) : Void
	{
		this.id_building = id_building;
		this.id_research = id_research;
		this.finish = finish;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `building_research` SET '
				+  '`id_building` = ' + db.quote(id_building)
				+', `id_research` = ' + db.quote(id_research)
				+', `finish` = ' + db.quote(finish)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}