// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class Buildings
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var name : String;
	public var shortname : String;
	public var id_building_category : Int;
	public var id_cost_category : Int;
	public var shape : String;
	public var offset : String;
	public var isProduction : Int;
	public var canAttack : Int;
	public var id_civ : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(name:String, shortname:String, id_building_category:Int, id_cost_category:Int, shape:String, offset:String, isProduction:Int, canAttack:Int, id_civ:Int) : Void
	{
		this.name = name;
		this.shortname = shortname;
		this.id_building_category = id_building_category;
		this.id_cost_category = id_cost_category;
		this.shape = shape;
		this.offset = offset;
		this.isProduction = isProduction;
		this.canAttack = canAttack;
		this.id_civ = id_civ;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `buildings` SET '
				+  '`name` = ' + db.quote(name)
				+', `shortname` = ' + db.quote(shortname)
				+', `id_building_category` = ' + db.quote(id_building_category)
				+', `id_cost_category` = ' + db.quote(id_cost_category)
				+', `shape` = ' + db.quote(shape)
				+', `offset` = ' + db.quote(offset)
				+', `isProduction` = ' + db.quote(isProduction)
				+', `canAttack` = ' + db.quote(canAttack)
				+', `id_civ` = ' + db.quote(id_civ)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}