// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class BuildingStatsManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.BuildingStats>;

	function get_query() : orm.SqlQuery<com.lak.models.BuildingStats>
	{
		return new orm.SqlQuery<com.lak.models.BuildingStats>("building_stats", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_buildings_stat_fields:Int, value:Int) : com.lak.models.BuildingStats
	{
		var _obj = new com.lak.models.BuildingStats(db, orm);
		_obj.id = id;
		_obj.id_buildings_stat_fields = id_buildings_stat_fields;
		_obj.value = value;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.BuildingStats
	{
		var _obj = new com.lak.models.BuildingStats(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_buildings_stat_fields = Reflect.field(d, 'id_buildings_stat_fields');
		_obj.value = Reflect.field(d, 'value');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.BuildingStats>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.BuildingStats
	{
		return getBySqlOne('SELECT * FROM `building_stats` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, id_buildings_stat_fields:Int, value:Int) : com.lak.models.BuildingStats
	{
		db.query('INSERT INTO `building_stats`(`id`, `id_buildings_stat_fields`, `value`) VALUES (' + db.quote(id) + ', ' + db.quote(id_buildings_stat_fields) + ', ' + db.quote(value) + ')');
		return newModelFromParams(id, id_buildings_stat_fields, value);
	}

	public function createNamed(data:{ id:Int, id_buildings_stat_fields:Int, value:Int }) : com.lak.models.BuildingStats
	{
		db.query('INSERT INTO `building_stats`(`id`, `id_buildings_stat_fields`, `value`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.id_buildings_stat_fields) + ', ' + db.quote(data.value) + ')');
		return newModelFromParams(data.id, data.id_buildings_stat_fields, data.value);
	}

	public function createOptional(data:{ id:Int, ?id_buildings_stat_fields:Int, ?value:Int }) : com.lak.models.BuildingStats
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?id_buildings_stat_fields:Int, ?value:Int }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'id_buildings_stat_fields')) { fields.push('`id_buildings_stat_fields`'); values.push(db.quote(data.id_buildings_stat_fields)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		db.query('INSERT INTO `building_stats`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `building_stats` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.BuildingStats>
	{
		return getBySqlMany('SELECT * FROM `building_stats`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.BuildingStats
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.BuildingStats>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.BuildingStats> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_buildings_stat_fields(id_buildings_stat_fields:Int, _order:String=null) : Array<com.lak.models.BuildingStats>
	{
		return getBySqlMany('SELECT * FROM `building_stats` WHERE `id_buildings_stat_fields` = ' + db.quote(id_buildings_stat_fields) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}