// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class CivilizationManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.Civilization>;

	function get_query() : orm.SqlQuery<com.lak.models.Civilization>
	{
		return new orm.SqlQuery<com.lak.models.Civilization>("civilization", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, shortname:String, icon:String) : com.lak.models.Civilization
	{
		var _obj = new com.lak.models.Civilization(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.shortname = shortname;
		_obj.icon = icon;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.Civilization
	{
		var _obj = new com.lak.models.Civilization(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.shortname = Reflect.field(d, 'shortname');
		_obj.icon = Reflect.field(d, 'icon');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.Civilization>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.Civilization
	{
		return getBySqlOne('SELECT * FROM `civilization` WHERE `id` = ' + db.quote(id));
	}

	public function create(name:String, shortname:String, icon:String) : com.lak.models.Civilization
	{
		db.query('INSERT INTO `civilization`(`name`, `shortname`, `icon`) VALUES (' + db.quote(name) + ', ' + db.quote(shortname) + ', ' + db.quote(icon) + ')');
		return newModelFromParams(db.lastInsertId(), name, shortname, icon);
	}

	public function createNamed(data:{ name:String, shortname:String, icon:String }) : com.lak.models.Civilization
	{
		db.query('INSERT INTO `civilization`(`name`, `shortname`, `icon`) VALUES (' + db.quote(data.name) + ', ' + db.quote(data.shortname) + ', ' + db.quote(data.icon) + ')');
		return newModelFromParams(db.lastInsertId(), data.name, data.shortname, data.icon);
	}

	public function createOptional(data:{ ?name:String, ?shortname:String, ?icon:String }) : com.lak.models.Civilization
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?name:String, ?shortname:String, ?icon:String }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'shortname')) { fields.push('`shortname`'); values.push(db.quote(data.shortname)); }
		if (Reflect.hasField(data, 'icon')) { fields.push('`icon`'); values.push(db.quote(data.icon)); }
		db.query('INSERT INTO `civilization`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `civilization` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.Civilization>
	{
		return getBySqlMany('SELECT * FROM `civilization`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.Civilization
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.Civilization>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.Civilization> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}