// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class Equipment
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_player : Int;
	public var id_hero : Int;
	public var id_weapon : Int;
	public var id_body_part : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_player:Int, id_hero:Int, id_weapon:Int, id_body_part:Int) : Void
	{
		this.id_player = id_player;
		this.id_hero = id_hero;
		this.id_weapon = id_weapon;
		this.id_body_part = id_body_part;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `equipment` SET '
				+  '`id_player` = ' + db.quote(id_player)
				+', `id_hero` = ' + db.quote(id_hero)
				+', `id_weapon` = ' + db.quote(id_weapon)
				+', `id_body_part` = ' + db.quote(id_body_part)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}