// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class HeroSkillsStat
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_hero_skill_category : Int;
	public var id_hero : Int;
	public var value : String;
	public var id_heroe_skill_fields : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_hero_skill_category:Int, id_hero:Int, value:String, id_heroe_skill_fields:Int) : Void
	{
		this.id_hero_skill_category = id_hero_skill_category;
		this.id_hero = id_hero;
		this.value = value;
		this.id_heroe_skill_fields = id_heroe_skill_fields;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `hero_skills_stat` SET '
				+  '`id_hero_skill_category` = ' + db.quote(id_hero_skill_category)
				+', `id_hero` = ' + db.quote(id_hero)
				+', `value` = ' + db.quote(value)
				+', `id_heroe_skill_fields` = ' + db.quote(id_heroe_skill_fields)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}