// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class HeroSkillsStatManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.HeroSkillsStat>;

	function get_query() : orm.SqlQuery<com.lak.models.HeroSkillsStat>
	{
		return new orm.SqlQuery<com.lak.models.HeroSkillsStat>("hero_skills_stat", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_hero_skill_category:Int, id_hero:Int, value:String, id_heroe_skill_fields:Int) : com.lak.models.HeroSkillsStat
	{
		var _obj = new com.lak.models.HeroSkillsStat(db, orm);
		_obj.id = id;
		_obj.id_hero_skill_category = id_hero_skill_category;
		_obj.id_hero = id_hero;
		_obj.value = value;
		_obj.id_heroe_skill_fields = id_heroe_skill_fields;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.HeroSkillsStat
	{
		var _obj = new com.lak.models.HeroSkillsStat(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_hero_skill_category = Reflect.field(d, 'id_hero_skill_category');
		_obj.id_hero = Reflect.field(d, 'id_hero');
		_obj.value = Reflect.field(d, 'value');
		_obj.id_heroe_skill_fields = Reflect.field(d, 'id_heroe_skill_fields');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.HeroSkillsStat>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.HeroSkillsStat
	{
		return getBySqlOne('SELECT * FROM `hero_skills_stat` WHERE `id` = ' + db.quote(id));
	}

	public function create(id_hero_skill_category:Int, id_hero:Int, value:String, id_heroe_skill_fields:Int) : com.lak.models.HeroSkillsStat
	{
		db.query('INSERT INTO `hero_skills_stat`(`id_hero_skill_category`, `id_hero`, `value`, `id_heroe_skill_fields`) VALUES (' + db.quote(id_hero_skill_category) + ', ' + db.quote(id_hero) + ', ' + db.quote(value) + ', ' + db.quote(id_heroe_skill_fields) + ')');
		return newModelFromParams(db.lastInsertId(), id_hero_skill_category, id_hero, value, id_heroe_skill_fields);
	}

	public function createNamed(data:{ id_hero_skill_category:Int, id_hero:Int, value:String, id_heroe_skill_fields:Int }) : com.lak.models.HeroSkillsStat
	{
		db.query('INSERT INTO `hero_skills_stat`(`id_hero_skill_category`, `id_hero`, `value`, `id_heroe_skill_fields`) VALUES (' + db.quote(data.id_hero_skill_category) + ', ' + db.quote(data.id_hero) + ', ' + db.quote(data.value) + ', ' + db.quote(data.id_heroe_skill_fields) + ')');
		return newModelFromParams(db.lastInsertId(), data.id_hero_skill_category, data.id_hero, data.value, data.id_heroe_skill_fields);
	}

	public function createOptional(data:{ ?id_hero_skill_category:Int, ?id_hero:Int, ?value:String, ?id_heroe_skill_fields:Int }) : com.lak.models.HeroSkillsStat
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?id_hero_skill_category:Int, ?id_hero:Int, ?value:String, ?id_heroe_skill_fields:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'id_hero_skill_category')) { fields.push('`id_hero_skill_category`'); values.push(db.quote(data.id_hero_skill_category)); }
		if (Reflect.hasField(data, 'id_hero')) { fields.push('`id_hero`'); values.push(db.quote(data.id_hero)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		if (Reflect.hasField(data, 'id_heroe_skill_fields')) { fields.push('`id_heroe_skill_fields`'); values.push(db.quote(data.id_heroe_skill_fields)); }
		db.query('INSERT INTO `hero_skills_stat`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `hero_skills_stat` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.HeroSkillsStat>
	{
		return getBySqlMany('SELECT * FROM `hero_skills_stat`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.HeroSkillsStat
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.HeroSkillsStat>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.HeroSkillsStat> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_hero_skill_category(id_hero_skill_category:Int, _order:String=null) : Array<com.lak.models.HeroSkillsStat>
	{
		return getBySqlMany('SELECT * FROM `hero_skills_stat` WHERE `id_hero_skill_category` = ' + db.quote(id_hero_skill_category) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_hero(id_hero:Int, _order:String=null) : Array<com.lak.models.HeroSkillsStat>
	{
		return getBySqlMany('SELECT * FROM `hero_skills_stat` WHERE `id_hero` = ' + db.quote(id_hero) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_heroe_skill_fields(id_heroe_skill_fields:Int, _order:String=null) : Array<com.lak.models.HeroSkillsStat>
	{
		return getBySqlMany('SELECT * FROM `hero_skills_stat` WHERE `id_heroe_skill_fields` = ' + db.quote(id_heroe_skill_fields) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}