// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class HeroesStatManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.HeroesStat>;

	function get_query() : orm.SqlQuery<com.lak.models.HeroesStat>
	{
		return new orm.SqlQuery<com.lak.models.HeroesStat>("heroes_stat", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_heroes:Int, id_stat_fields:Int, value:Int) : com.lak.models.HeroesStat
	{
		var _obj = new com.lak.models.HeroesStat(db, orm);
		_obj.id = id;
		_obj.id_heroes = id_heroes;
		_obj.id_stat_fields = id_stat_fields;
		_obj.value = value;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.HeroesStat
	{
		var _obj = new com.lak.models.HeroesStat(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_heroes = Reflect.field(d, 'id_heroes');
		_obj.id_stat_fields = Reflect.field(d, 'id_stat_fields');
		_obj.value = Reflect.field(d, 'value');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.HeroesStat>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.HeroesStat
	{
		return getBySqlOne('SELECT * FROM `heroes_stat` WHERE `id` = ' + db.quote(id));
	}

	public function create(id_heroes:Int, id_stat_fields:Int, value:Int) : com.lak.models.HeroesStat
	{
		db.query('INSERT INTO `heroes_stat`(`id_heroes`, `id_stat_fields`, `value`) VALUES (' + db.quote(id_heroes) + ', ' + db.quote(id_stat_fields) + ', ' + db.quote(value) + ')');
		return newModelFromParams(db.lastInsertId(), id_heroes, id_stat_fields, value);
	}

	public function createNamed(data:{ id_heroes:Int, id_stat_fields:Int, value:Int }) : com.lak.models.HeroesStat
	{
		db.query('INSERT INTO `heroes_stat`(`id_heroes`, `id_stat_fields`, `value`) VALUES (' + db.quote(data.id_heroes) + ', ' + db.quote(data.id_stat_fields) + ', ' + db.quote(data.value) + ')');
		return newModelFromParams(db.lastInsertId(), data.id_heroes, data.id_stat_fields, data.value);
	}

	public function createOptional(data:{ ?id_heroes:Int, ?id_stat_fields:Int, ?value:Int }) : com.lak.models.HeroesStat
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?id_heroes:Int, ?id_stat_fields:Int, ?value:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'id_heroes')) { fields.push('`id_heroes`'); values.push(db.quote(data.id_heroes)); }
		if (Reflect.hasField(data, 'id_stat_fields')) { fields.push('`id_stat_fields`'); values.push(db.quote(data.id_stat_fields)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		db.query('INSERT INTO `heroes_stat`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `heroes_stat` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.HeroesStat>
	{
		return getBySqlMany('SELECT * FROM `heroes_stat`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.HeroesStat
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.HeroesStat>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.HeroesStat> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_heroes(id_heroes:Int, _order:String=null) : Array<com.lak.models.HeroesStat>
	{
		return getBySqlMany('SELECT * FROM `heroes_stat` WHERE `id_heroes` = ' + db.quote(id_heroes) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_stat_fields(id_stat_fields:Int, _order:String=null) : Array<com.lak.models.HeroesStat>
	{
		return getBySqlMany('SELECT * FROM `heroes_stat` WHERE `id_stat_fields` = ' + db.quote(id_stat_fields) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}