// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class HeroSkillCategoryManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.HeroSkillCategory>;

	function get_query() : orm.SqlQuery<com.lak.models.HeroSkillCategory>
	{
		return new orm.SqlQuery<com.lak.models.HeroSkillCategory>("hero_skill_category", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, shortname:String) : com.lak.models.HeroSkillCategory
	{
		var _obj = new com.lak.models.HeroSkillCategory(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.shortname = shortname;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.HeroSkillCategory
	{
		var _obj = new com.lak.models.HeroSkillCategory(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.shortname = Reflect.field(d, 'shortname');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.HeroSkillCategory>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.HeroSkillCategory
	{
		return getBySqlOne('SELECT * FROM `hero_skill_category` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, name:String, shortname:String) : com.lak.models.HeroSkillCategory
	{
		db.query('INSERT INTO `hero_skill_category`(`id`, `name`, `shortname`) VALUES (' + db.quote(id) + ', ' + db.quote(name) + ', ' + db.quote(shortname) + ')');
		return newModelFromParams(id, name, shortname);
	}

	public function createNamed(data:{ id:Int, name:String, shortname:String }) : com.lak.models.HeroSkillCategory
	{
		db.query('INSERT INTO `hero_skill_category`(`id`, `name`, `shortname`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.name) + ', ' + db.quote(data.shortname) + ')');
		return newModelFromParams(data.id, data.name, data.shortname);
	}

	public function createOptional(data:{ id:Int, ?name:String, ?shortname:String }) : com.lak.models.HeroSkillCategory
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?name:String, ?shortname:String }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'shortname')) { fields.push('`shortname`'); values.push(db.quote(data.shortname)); }
		db.query('INSERT INTO `hero_skill_category`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `hero_skill_category` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.HeroSkillCategory>
	{
		return getBySqlMany('SELECT * FROM `hero_skill_category`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.HeroSkillCategory
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.HeroSkillCategory>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.HeroSkillCategory> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}