// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class HeroesSkillsFieldsManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.HeroesSkillsFields>;

	function get_query() : orm.SqlQuery<com.lak.models.HeroesSkillsFields>
	{
		return new orm.SqlQuery<com.lak.models.HeroesSkillsFields>("heroes_skills_fields", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, short:String, icon:String) : com.lak.models.HeroesSkillsFields
	{
		var _obj = new com.lak.models.HeroesSkillsFields(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.short = short;
		_obj.icon = icon;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.HeroesSkillsFields
	{
		var _obj = new com.lak.models.HeroesSkillsFields(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.short = Reflect.field(d, 'short');
		_obj.icon = Reflect.field(d, 'icon');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.HeroesSkillsFields>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.HeroesSkillsFields
	{
		return getBySqlOne('SELECT * FROM `heroes_skills_fields` WHERE `id` = ' + db.quote(id));
	}

	public function create(name:String, short:String, icon:String) : com.lak.models.HeroesSkillsFields
	{
		db.query('INSERT INTO `heroes_skills_fields`(`name`, `short`, `icon`) VALUES (' + db.quote(name) + ', ' + db.quote(short) + ', ' + db.quote(icon) + ')');
		return newModelFromParams(db.lastInsertId(), name, short, icon);
	}

	public function createNamed(data:{ name:String, short:String, icon:String }) : com.lak.models.HeroesSkillsFields
	{
		db.query('INSERT INTO `heroes_skills_fields`(`name`, `short`, `icon`) VALUES (' + db.quote(data.name) + ', ' + db.quote(data.short) + ', ' + db.quote(data.icon) + ')');
		return newModelFromParams(db.lastInsertId(), data.name, data.short, data.icon);
	}

	public function createOptional(data:{ ?name:String, ?short:String, ?icon:String }) : com.lak.models.HeroesSkillsFields
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?name:String, ?short:String, ?icon:String }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'short')) { fields.push('`short`'); values.push(db.quote(data.short)); }
		if (Reflect.hasField(data, 'icon')) { fields.push('`icon`'); values.push(db.quote(data.icon)); }
		db.query('INSERT INTO `heroes_skills_fields`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `heroes_skills_fields` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.HeroesSkillsFields>
	{
		return getBySqlMany('SELECT * FROM `heroes_skills_fields`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.HeroesSkillsFields
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.HeroesSkillsFields>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.HeroesSkillsFields> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}