// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class HeroesStatFieldsManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.HeroesStatFields>;

	function get_query() : orm.SqlQuery<com.lak.models.HeroesStatFields>
	{
		return new orm.SqlQuery<com.lak.models.HeroesStatFields>("heroes_stat_fields", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, short_name:String, id_heroe_skills:String) : com.lak.models.HeroesStatFields
	{
		var _obj = new com.lak.models.HeroesStatFields(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.short_name = short_name;
		_obj.id_heroe_skills = id_heroe_skills;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.HeroesStatFields
	{
		var _obj = new com.lak.models.HeroesStatFields(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.short_name = Reflect.field(d, 'short_name');
		_obj.id_heroe_skills = Reflect.field(d, 'id_heroe_skills');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.HeroesStatFields>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.HeroesStatFields
	{
		return getBySqlOne('SELECT * FROM `heroes_stat_fields` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, name:String, short_name:String, id_heroe_skills:String) : com.lak.models.HeroesStatFields
	{
		db.query('INSERT INTO `heroes_stat_fields`(`id`, `name`, `short_name`, `id_heroe_skills`) VALUES (' + db.quote(id) + ', ' + db.quote(name) + ', ' + db.quote(short_name) + ', ' + db.quote(id_heroe_skills) + ')');
		return newModelFromParams(id, name, short_name, id_heroe_skills);
	}

	public function createNamed(data:{ id:Int, name:String, short_name:String, id_heroe_skills:String }) : com.lak.models.HeroesStatFields
	{
		db.query('INSERT INTO `heroes_stat_fields`(`id`, `name`, `short_name`, `id_heroe_skills`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.name) + ', ' + db.quote(data.short_name) + ', ' + db.quote(data.id_heroe_skills) + ')');
		return newModelFromParams(data.id, data.name, data.short_name, data.id_heroe_skills);
	}

	public function createOptional(data:{ id:Int, ?name:String, ?short_name:String, ?id_heroe_skills:String }) : com.lak.models.HeroesStatFields
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?name:String, ?short_name:String, ?id_heroe_skills:String }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'short_name')) { fields.push('`short_name`'); values.push(db.quote(data.short_name)); }
		if (Reflect.hasField(data, 'id_heroe_skills')) { fields.push('`id_heroe_skills`'); values.push(db.quote(data.id_heroe_skills)); }
		db.query('INSERT INTO `heroes_stat_fields`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `heroes_stat_fields` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.HeroesStatFields>
	{
		return getBySqlMany('SELECT * FROM `heroes_stat_fields`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.HeroesStatFields
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.HeroesStatFields>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.HeroesStatFields> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}