// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MoralityStat
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_morality : Int;
	public var value : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_morality:Int, value:Int) : Void
	{
		this.id_morality = id_morality;
		this.value = value;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `morality_stat` SET '
				+  '`id_morality` = ' + db.quote(id_morality)
				+', `value` = ' + db.quote(value)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}