// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MoralityManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.Morality>;

	function get_query() : orm.SqlQuery<com.lak.models.Morality>
	{
		return new orm.SqlQuery<com.lak.models.Morality>("morality", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_king:Int) : com.lak.models.Morality
	{
		var _obj = new com.lak.models.Morality(db, orm);
		_obj.id = id;
		_obj.id_king = id_king;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.Morality
	{
		var _obj = new com.lak.models.Morality(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_king = Reflect.field(d, 'id_king');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.Morality>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.Morality
	{
		return getBySqlOne('SELECT * FROM `morality` WHERE `id` = ' + db.quote(id));
	}

	public function create(id_king:Int) : com.lak.models.Morality
	{
		db.query('INSERT INTO `morality`(`id_king`) VALUES (' + db.quote(id_king) + ')');
		return newModelFromParams(db.lastInsertId(), id_king);
	}

	public function createNamed(data:{ id_king:Int }) : com.lak.models.Morality
	{
		db.query('INSERT INTO `morality`(`id_king`) VALUES (' + db.quote(data.id_king) + ')');
		return newModelFromParams(db.lastInsertId(), data.id_king);
	}

	public function createOptional(data:{ ?id_king:Int }) : com.lak.models.Morality
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?id_king:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'id_king')) { fields.push('`id_king`'); values.push(db.quote(data.id_king)); }
		db.query('INSERT INTO `morality`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `morality` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.Morality>
	{
		return getBySqlMany('SELECT * FROM `morality`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.Morality
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.Morality>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.Morality> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_king(id_king:Int, _order:String=null) : Array<com.lak.models.Morality>
	{
		return getBySqlMany('SELECT * FROM `morality` WHERE `id_king` = ' + db.quote(id_king) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}