// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MoralityFields
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var name : String;
	public var id_morality_stat : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(name:String, id_morality_stat:Int) : Void
	{
		this.name = name;
		this.id_morality_stat = id_morality_stat;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `morality_fields` SET '
				+  '`name` = ' + db.quote(name)
				+', `id_morality_stat` = ' + db.quote(id_morality_stat)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}