// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MoralityStatManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.MoralityStat>;

	function get_query() : orm.SqlQuery<com.lak.models.MoralityStat>
	{
		return new orm.SqlQuery<com.lak.models.MoralityStat>("morality_stat", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_morality:Int, value:Int) : com.lak.models.MoralityStat
	{
		var _obj = new com.lak.models.MoralityStat(db, orm);
		_obj.id = id;
		_obj.id_morality = id_morality;
		_obj.value = value;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.MoralityStat
	{
		var _obj = new com.lak.models.MoralityStat(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_morality = Reflect.field(d, 'id_morality');
		_obj.value = Reflect.field(d, 'value');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.MoralityStat>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.MoralityStat
	{
		return getBySqlOne('SELECT * FROM `morality_stat` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, id_morality:Int, value:Int) : com.lak.models.MoralityStat
	{
		db.query('INSERT INTO `morality_stat`(`id`, `id_morality`, `value`) VALUES (' + db.quote(id) + ', ' + db.quote(id_morality) + ', ' + db.quote(value) + ')');
		return newModelFromParams(id, id_morality, value);
	}

	public function createNamed(data:{ id:Int, id_morality:Int, value:Int }) : com.lak.models.MoralityStat
	{
		db.query('INSERT INTO `morality_stat`(`id`, `id_morality`, `value`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.id_morality) + ', ' + db.quote(data.value) + ')');
		return newModelFromParams(data.id, data.id_morality, data.value);
	}

	public function createOptional(data:{ id:Int, ?id_morality:Int, ?value:Int }) : com.lak.models.MoralityStat
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?id_morality:Int, ?value:Int }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'id_morality')) { fields.push('`id_morality`'); values.push(db.quote(data.id_morality)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		db.query('INSERT INTO `morality_stat`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `morality_stat` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.MoralityStat>
	{
		return getBySqlMany('SELECT * FROM `morality_stat`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.MoralityStat
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.MoralityStat>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.MoralityStat> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_morality(id_morality:Int, _order:String=null) : Array<com.lak.models.MoralityStat>
	{
		return getBySqlMany('SELECT * FROM `morality_stat` WHERE `id_morality` = ' + db.quote(id_morality) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}