// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MoralityFieldsManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.MoralityFields>;

	function get_query() : orm.SqlQuery<com.lak.models.MoralityFields>
	{
		return new orm.SqlQuery<com.lak.models.MoralityFields>("morality_fields", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, id_morality_stat:Int) : com.lak.models.MoralityFields
	{
		var _obj = new com.lak.models.MoralityFields(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.id_morality_stat = id_morality_stat;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.MoralityFields
	{
		var _obj = new com.lak.models.MoralityFields(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.id_morality_stat = Reflect.field(d, 'id_morality_stat');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.MoralityFields>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.MoralityFields
	{
		return getBySqlOne('SELECT * FROM `morality_fields` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, name:String, id_morality_stat:Int) : com.lak.models.MoralityFields
	{
		db.query('INSERT INTO `morality_fields`(`id`, `name`, `id_morality_stat`) VALUES (' + db.quote(id) + ', ' + db.quote(name) + ', ' + db.quote(id_morality_stat) + ')');
		return newModelFromParams(id, name, id_morality_stat);
	}

	public function createNamed(data:{ id:Int, name:String, id_morality_stat:Int }) : com.lak.models.MoralityFields
	{
		db.query('INSERT INTO `morality_fields`(`id`, `name`, `id_morality_stat`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.name) + ', ' + db.quote(data.id_morality_stat) + ')');
		return newModelFromParams(data.id, data.name, data.id_morality_stat);
	}

	public function createOptional(data:{ id:Int, ?name:String, ?id_morality_stat:Int }) : com.lak.models.MoralityFields
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?name:String, ?id_morality_stat:Int }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'id_morality_stat')) { fields.push('`id_morality_stat`'); values.push(db.quote(data.id_morality_stat)); }
		db.query('INSERT INTO `morality_fields`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `morality_fields` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.MoralityFields>
	{
		return getBySqlMany('SELECT * FROM `morality_fields`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.MoralityFields
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.MoralityFields>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.MoralityFields> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_morality_stat(id_morality_stat:Int, _order:String=null) : Array<com.lak.models.MoralityFields>
	{
		return getBySqlMany('SELECT * FROM `morality_fields` WHERE `id_morality_stat` = ' + db.quote(id_morality_stat) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}