// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class Morality
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_king : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_king:Int) : Void
	{
		this.id_king = id_king;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `morality` SET '
				+  '`id_king` = ' + db.quote(id_king)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}