// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MountManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.Mount>;

	function get_query() : orm.SqlQuery<com.lak.models.Mount>
	{
		return new orm.SqlQuery<com.lak.models.Mount>("mount", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_mount_category:Int, name:String) : com.lak.models.Mount
	{
		var _obj = new com.lak.models.Mount(db, orm);
		_obj.id = id;
		_obj.id_mount_category = id_mount_category;
		_obj.name = name;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.Mount
	{
		var _obj = new com.lak.models.Mount(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_mount_category = Reflect.field(d, 'id_mount_category');
		_obj.name = Reflect.field(d, 'name');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.Mount>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.Mount
	{
		return getBySqlOne('SELECT * FROM `mount` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, id_mount_category:Int, name:String) : com.lak.models.Mount
	{
		db.query('INSERT INTO `mount`(`id`, `id_mount_category`, `name`) VALUES (' + db.quote(id) + ', ' + db.quote(id_mount_category) + ', ' + db.quote(name) + ')');
		return newModelFromParams(id, id_mount_category, name);
	}

	public function createNamed(data:{ id:Int, id_mount_category:Int, name:String }) : com.lak.models.Mount
	{
		db.query('INSERT INTO `mount`(`id`, `id_mount_category`, `name`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.id_mount_category) + ', ' + db.quote(data.name) + ')');
		return newModelFromParams(data.id, data.id_mount_category, data.name);
	}

	public function createOptional(data:{ id:Int, ?id_mount_category:Int, ?name:String }) : com.lak.models.Mount
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?id_mount_category:Int, ?name:String }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'id_mount_category')) { fields.push('`id_mount_category`'); values.push(db.quote(data.id_mount_category)); }
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		db.query('INSERT INTO `mount`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `mount` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.Mount>
	{
		return getBySqlMany('SELECT * FROM `mount`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.Mount
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.Mount>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.Mount> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_mount_category(id_mount_category:Int, _order:String=null) : Array<com.lak.models.Mount>
	{
		return getBySqlMany('SELECT * FROM `mount` WHERE `id_mount_category` = ' + db.quote(id_mount_category) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}