// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MountStat
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_stat_field : Int;
	public var value : Int;
	public var id_mount : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_stat_field:Int, value:Int, id_mount:Int) : Void
	{
		this.id_stat_field = id_stat_field;
		this.value = value;
		this.id_mount = id_mount;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `mount_stat` SET '
				+  '`id_stat_field` = ' + db.quote(id_stat_field)
				+', `value` = ' + db.quote(value)
				+', `id_mount` = ' + db.quote(id_mount)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}