// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class MountStatFieldsManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.MountStatFields>;

	function get_query() : orm.SqlQuery<com.lak.models.MountStatFields>
	{
		return new orm.SqlQuery<com.lak.models.MountStatFields>("mount_stat_fields", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, short:String, value:Int) : com.lak.models.MountStatFields
	{
		var _obj = new com.lak.models.MountStatFields(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.short = short;
		_obj.value = value;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.MountStatFields
	{
		var _obj = new com.lak.models.MountStatFields(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.short = Reflect.field(d, 'short');
		_obj.value = Reflect.field(d, 'value');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.MountStatFields>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.MountStatFields
	{
		return getBySqlOne('SELECT * FROM `mount_stat_fields` WHERE `id` = ' + db.quote(id));
	}

	public function create(name:String, short:String, value:Int) : com.lak.models.MountStatFields
	{
		db.query('INSERT INTO `mount_stat_fields`(`name`, `short`, `value`) VALUES (' + db.quote(name) + ', ' + db.quote(short) + ', ' + db.quote(value) + ')');
		return newModelFromParams(db.lastInsertId(), name, short, value);
	}

	public function createNamed(data:{ name:String, short:String, value:Int }) : com.lak.models.MountStatFields
	{
		db.query('INSERT INTO `mount_stat_fields`(`name`, `short`, `value`) VALUES (' + db.quote(data.name) + ', ' + db.quote(data.short) + ', ' + db.quote(data.value) + ')');
		return newModelFromParams(db.lastInsertId(), data.name, data.short, data.value);
	}

	public function createOptional(data:{ ?name:String, ?short:String, ?value:Int }) : com.lak.models.MountStatFields
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?name:String, ?short:String, ?value:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'short')) { fields.push('`short`'); values.push(db.quote(data.short)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		db.query('INSERT INTO `mount_stat_fields`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `mount_stat_fields` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.MountStatFields>
	{
		return getBySqlMany('SELECT * FROM `mount_stat_fields`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.MountStatFields
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.MountStatFields>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.MountStatFields> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}