// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class PlayerManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.Player>;

	function get_query() : orm.SqlQuery<com.lak.models.Player>
	{
		return new orm.SqlQuery<com.lak.models.Player>("player", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, id_civ:Int, score:Int) : com.lak.models.Player
	{
		var _obj = new com.lak.models.Player(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.id_civ = id_civ;
		_obj.score = score;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.Player
	{
		var _obj = new com.lak.models.Player(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.id_civ = Reflect.field(d, 'id_civ');
		_obj.score = Reflect.field(d, 'score');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.Player>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.Player
	{
		return getBySqlOne('SELECT * FROM `player` WHERE `id` = ' + db.quote(id));
	}

	public function create(name:String, id_civ:Int, score:Int) : com.lak.models.Player
	{
		db.query('INSERT INTO `player`(`name`, `id_civ`, `score`) VALUES (' + db.quote(name) + ', ' + db.quote(id_civ) + ', ' + db.quote(score) + ')');
		return newModelFromParams(db.lastInsertId(), name, id_civ, score);
	}

	public function createNamed(data:{ name:String, id_civ:Int, score:Int }) : com.lak.models.Player
	{
		db.query('INSERT INTO `player`(`name`, `id_civ`, `score`) VALUES (' + db.quote(data.name) + ', ' + db.quote(data.id_civ) + ', ' + db.quote(data.score) + ')');
		return newModelFromParams(db.lastInsertId(), data.name, data.id_civ, data.score);
	}

	public function createOptional(data:{ ?name:String, ?id_civ:Int, ?score:Int }) : com.lak.models.Player
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?name:String, ?id_civ:Int, ?score:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'id_civ')) { fields.push('`id_civ`'); values.push(db.quote(data.id_civ)); }
		if (Reflect.hasField(data, 'score')) { fields.push('`score`'); values.push(db.quote(data.score)); }
		db.query('INSERT INTO `player`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `player` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.Player>
	{
		return getBySqlMany('SELECT * FROM `player`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.Player
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.Player>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.Player> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_civ(id_civ:Int, _order:String=null) : Array<com.lak.models.Player>
	{
		return getBySqlMany('SELECT * FROM `player` WHERE `id_civ` = ' + db.quote(id_civ) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}