// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class Player
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var name : String;
	public var id_civ : Int;
	public var score : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(name:String, id_civ:Int, score:Int) : Void
	{
		this.name = name;
		this.id_civ = id_civ;
		this.score = score;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `player` SET '
				+  '`name` = ' + db.quote(name)
				+', `id_civ` = ' + db.quote(id_civ)
				+', `score` = ' + db.quote(score)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}