// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class PlayerRessources
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_player : Int;
	public var id_ressource_type : Int;
	public var value : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_player:Int, id_ressource_type:Int, value:Int) : Void
	{
		this.id_player = id_player;
		this.id_ressource_type = id_ressource_type;
		this.value = value;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `player_ressources` SET '
				+  '`id_player` = ' + db.quote(id_player)
				+', `id_ressource_type` = ' + db.quote(id_ressource_type)
				+', `value` = ' + db.quote(value)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}