// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class PlayerRessourcesManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.PlayerRessources>;

	function get_query() : orm.SqlQuery<com.lak.models.PlayerRessources>
	{
		return new orm.SqlQuery<com.lak.models.PlayerRessources>("player_ressources", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_player:Int, id_ressource_type:Int, value:Int) : com.lak.models.PlayerRessources
	{
		var _obj = new com.lak.models.PlayerRessources(db, orm);
		_obj.id = id;
		_obj.id_player = id_player;
		_obj.id_ressource_type = id_ressource_type;
		_obj.value = value;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.PlayerRessources
	{
		var _obj = new com.lak.models.PlayerRessources(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_player = Reflect.field(d, 'id_player');
		_obj.id_ressource_type = Reflect.field(d, 'id_ressource_type');
		_obj.value = Reflect.field(d, 'value');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.PlayerRessources>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.PlayerRessources
	{
		return getBySqlOne('SELECT * FROM `player_ressources` WHERE `id` = ' + db.quote(id));
	}

	public function create(id_player:Int, id_ressource_type:Int, value:Int) : com.lak.models.PlayerRessources
	{
		db.query('INSERT INTO `player_ressources`(`id_player`, `id_ressource_type`, `value`) VALUES (' + db.quote(id_player) + ', ' + db.quote(id_ressource_type) + ', ' + db.quote(value) + ')');
		return newModelFromParams(db.lastInsertId(), id_player, id_ressource_type, value);
	}

	public function createNamed(data:{ id_player:Int, id_ressource_type:Int, value:Int }) : com.lak.models.PlayerRessources
	{
		db.query('INSERT INTO `player_ressources`(`id_player`, `id_ressource_type`, `value`) VALUES (' + db.quote(data.id_player) + ', ' + db.quote(data.id_ressource_type) + ', ' + db.quote(data.value) + ')');
		return newModelFromParams(db.lastInsertId(), data.id_player, data.id_ressource_type, data.value);
	}

	public function createOptional(data:{ ?id_player:Int, ?id_ressource_type:Int, ?value:Int }) : com.lak.models.PlayerRessources
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?id_player:Int, ?id_ressource_type:Int, ?value:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'id_player')) { fields.push('`id_player`'); values.push(db.quote(data.id_player)); }
		if (Reflect.hasField(data, 'id_ressource_type')) { fields.push('`id_ressource_type`'); values.push(db.quote(data.id_ressource_type)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		db.query('INSERT INTO `player_ressources`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `player_ressources` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.PlayerRessources>
	{
		return getBySqlMany('SELECT * FROM `player_ressources`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.PlayerRessources
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.PlayerRessources>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.PlayerRessources> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_player(id_player:Int, _order:String=null) : Array<com.lak.models.PlayerRessources>
	{
		return getBySqlMany('SELECT * FROM `player_ressources` WHERE `id_player` = ' + db.quote(id_player) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_ressource_type(id_ressource_type:Int, _order:String=null) : Array<com.lak.models.PlayerRessources>
	{
		return getBySqlMany('SELECT * FROM `player_ressources` WHERE `id_ressource_type` = ' + db.quote(id_ressource_type) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}