// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class ResearchNeedsManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.ResearchNeeds>;

	function get_query() : orm.SqlQuery<com.lak.models.ResearchNeeds>
	{
		return new orm.SqlQuery<com.lak.models.ResearchNeeds>("research_needs", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_needs_category:Int, id_research:Int, value:Int) : com.lak.models.ResearchNeeds
	{
		var _obj = new com.lak.models.ResearchNeeds(db, orm);
		_obj.id = id;
		_obj.id_needs_category = id_needs_category;
		_obj.id_research = id_research;
		_obj.value = value;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.ResearchNeeds
	{
		var _obj = new com.lak.models.ResearchNeeds(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_needs_category = Reflect.field(d, 'id_needs_category');
		_obj.id_research = Reflect.field(d, 'id_research');
		_obj.value = Reflect.field(d, 'value');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.ResearchNeeds>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.ResearchNeeds
	{
		return getBySqlOne('SELECT * FROM `research_needs` WHERE `id` = ' + db.quote(id));
	}

	public function create(id_needs_category:Int, id_research:Int, value:Int) : com.lak.models.ResearchNeeds
	{
		db.query('INSERT INTO `research_needs`(`id_needs_category`, `id_research`, `value`) VALUES (' + db.quote(id_needs_category) + ', ' + db.quote(id_research) + ', ' + db.quote(value) + ')');
		return newModelFromParams(db.lastInsertId(), id_needs_category, id_research, value);
	}

	public function createNamed(data:{ id_needs_category:Int, id_research:Int, value:Int }) : com.lak.models.ResearchNeeds
	{
		db.query('INSERT INTO `research_needs`(`id_needs_category`, `id_research`, `value`) VALUES (' + db.quote(data.id_needs_category) + ', ' + db.quote(data.id_research) + ', ' + db.quote(data.value) + ')');
		return newModelFromParams(db.lastInsertId(), data.id_needs_category, data.id_research, data.value);
	}

	public function createOptional(data:{ ?id_needs_category:Int, ?id_research:Int, ?value:Int }) : com.lak.models.ResearchNeeds
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?id_needs_category:Int, ?id_research:Int, ?value:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'id_needs_category')) { fields.push('`id_needs_category`'); values.push(db.quote(data.id_needs_category)); }
		if (Reflect.hasField(data, 'id_research')) { fields.push('`id_research`'); values.push(db.quote(data.id_research)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		db.query('INSERT INTO `research_needs`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `research_needs` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.ResearchNeeds>
	{
		return getBySqlMany('SELECT * FROM `research_needs`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.ResearchNeeds
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.ResearchNeeds>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.ResearchNeeds> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_needs_category(id_needs_category:Int, _order:String=null) : Array<com.lak.models.ResearchNeeds>
	{
		return getBySqlMany('SELECT * FROM `research_needs` WHERE `id_needs_category` = ' + db.quote(id_needs_category) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_research(id_research:Int, _order:String=null) : Array<com.lak.models.ResearchNeeds>
	{
		return getBySqlMany('SELECT * FROM `research_needs` WHERE `id_research` = ' + db.quote(id_research) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}