// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class ResearchNeeds
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_needs_category : Int;
	public var id_research : Int;
	public var value : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_needs_category:Int, id_research:Int, value:Int) : Void
	{
		this.id_needs_category = id_needs_category;
		this.id_research = id_research;
		this.value = value;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `research_needs` SET '
				+  '`id_needs_category` = ' + db.quote(id_needs_category)
				+', `id_research` = ' + db.quote(id_research)
				+', `value` = ' + db.quote(value)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}