// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class RessourcesType
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var name : String;
	public var icon : String;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(name:String, icon:String) : Void
	{
		this.name = name;
		this.icon = icon;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `ressources_type` SET '
				+  '`name` = ' + db.quote(name)
				+', `icon` = ' + db.quote(icon)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}