// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class StrengthManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.Strength>;

	function get_query() : orm.SqlQuery<com.lak.models.Strength>
	{
		return new orm.SqlQuery<com.lak.models.Strength>("strength", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, value:Int, id_stat_field:Int) : com.lak.models.Strength
	{
		var _obj = new com.lak.models.Strength(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.value = value;
		_obj.id_stat_field = id_stat_field;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.Strength
	{
		var _obj = new com.lak.models.Strength(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.value = Reflect.field(d, 'value');
		_obj.id_stat_field = Reflect.field(d, 'id_stat_field');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.Strength>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.Strength
	{
		return getBySqlOne('SELECT * FROM `strength` WHERE `id` = ' + db.quote(id));
	}

	public function create(name:String, value:Int, id_stat_field:Int) : com.lak.models.Strength
	{
		db.query('INSERT INTO `strength`(`name`, `value`, `id_stat_field`) VALUES (' + db.quote(name) + ', ' + db.quote(value) + ', ' + db.quote(id_stat_field) + ')');
		return newModelFromParams(db.lastInsertId(), name, value, id_stat_field);
	}

	public function createNamed(data:{ name:String, value:Int, id_stat_field:Int }) : com.lak.models.Strength
	{
		db.query('INSERT INTO `strength`(`name`, `value`, `id_stat_field`) VALUES (' + db.quote(data.name) + ', ' + db.quote(data.value) + ', ' + db.quote(data.id_stat_field) + ')');
		return newModelFromParams(db.lastInsertId(), data.name, data.value, data.id_stat_field);
	}

	public function createOptional(data:{ ?name:String, ?value:Int, ?id_stat_field:Int }) : com.lak.models.Strength
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?name:String, ?value:Int, ?id_stat_field:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		if (Reflect.hasField(data, 'id_stat_field')) { fields.push('`id_stat_field`'); values.push(db.quote(data.id_stat_field)); }
		db.query('INSERT INTO `strength`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `strength` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.Strength>
	{
		return getBySqlMany('SELECT * FROM `strength`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.Strength
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.Strength>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.Strength> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}