// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class Units
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_type : Int;
	public var id_mount : Int;
	public var id_civ : Int;
	public var name : String;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_type:Int, id_mount:Int, id_civ:Int, name:String) : Void
	{
		this.id_type = id_type;
		this.id_mount = id_mount;
		this.id_civ = id_civ;
		this.name = name;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `units` SET '
				+  '`id_type` = ' + db.quote(id_type)
				+', `id_mount` = ' + db.quote(id_mount)
				+', `id_civ` = ' + db.quote(id_civ)
				+', `name` = ' + db.quote(name)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}