// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class UnitStatManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.UnitStat>;

	function get_query() : orm.SqlQuery<com.lak.models.UnitStat>
	{
		return new orm.SqlQuery<com.lak.models.UnitStat>("unit_stat", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_fields:Int, id_unit:Int, value:Int) : com.lak.models.UnitStat
	{
		var _obj = new com.lak.models.UnitStat(db, orm);
		_obj.id = id;
		_obj.id_fields = id_fields;
		_obj.id_unit = id_unit;
		_obj.value = value;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.UnitStat
	{
		var _obj = new com.lak.models.UnitStat(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_fields = Reflect.field(d, 'id_fields');
		_obj.id_unit = Reflect.field(d, 'id_unit');
		_obj.value = Reflect.field(d, 'value');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.UnitStat>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.UnitStat
	{
		return getBySqlOne('SELECT * FROM `unit_stat` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, id_fields:Int, id_unit:Int, value:Int) : com.lak.models.UnitStat
	{
		db.query('INSERT INTO `unit_stat`(`id`, `id_fields`, `id_unit`, `value`) VALUES (' + db.quote(id) + ', ' + db.quote(id_fields) + ', ' + db.quote(id_unit) + ', ' + db.quote(value) + ')');
		return newModelFromParams(id, id_fields, id_unit, value);
	}

	public function createNamed(data:{ id:Int, id_fields:Int, id_unit:Int, value:Int }) : com.lak.models.UnitStat
	{
		db.query('INSERT INTO `unit_stat`(`id`, `id_fields`, `id_unit`, `value`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.id_fields) + ', ' + db.quote(data.id_unit) + ', ' + db.quote(data.value) + ')');
		return newModelFromParams(data.id, data.id_fields, data.id_unit, data.value);
	}

	public function createOptional(data:{ id:Int, ?id_fields:Int, ?id_unit:Int, ?value:Int }) : com.lak.models.UnitStat
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?id_fields:Int, ?id_unit:Int, ?value:Int }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'id_fields')) { fields.push('`id_fields`'); values.push(db.quote(data.id_fields)); }
		if (Reflect.hasField(data, 'id_unit')) { fields.push('`id_unit`'); values.push(db.quote(data.id_unit)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		db.query('INSERT INTO `unit_stat`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `unit_stat` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.UnitStat>
	{
		return getBySqlMany('SELECT * FROM `unit_stat`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.UnitStat
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.UnitStat>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.UnitStat> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_fields(id_fields:Int, _order:String=null) : Array<com.lak.models.UnitStat>
	{
		return getBySqlMany('SELECT * FROM `unit_stat` WHERE `id_fields` = ' + db.quote(id_fields) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_unit(id_unit:Int, _order:String=null) : Array<com.lak.models.UnitStat>
	{
		return getBySqlMany('SELECT * FROM `unit_stat` WHERE `id_unit` = ' + db.quote(id_unit) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}