// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class WeaponCategoryManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.WeaponCategory>;

	function get_query() : orm.SqlQuery<com.lak.models.WeaponCategory>
	{
		return new orm.SqlQuery<com.lak.models.WeaponCategory>("weapon_category", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, name:String, id_body_part:Int) : com.lak.models.WeaponCategory
	{
		var _obj = new com.lak.models.WeaponCategory(db, orm);
		_obj.id = id;
		_obj.name = name;
		_obj.id_body_part = id_body_part;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.WeaponCategory
	{
		var _obj = new com.lak.models.WeaponCategory(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.name = Reflect.field(d, 'name');
		_obj.id_body_part = Reflect.field(d, 'id_body_part');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.WeaponCategory>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.WeaponCategory
	{
		return getBySqlOne('SELECT * FROM `weapon_category` WHERE `id` = ' + db.quote(id));
	}

	public function create(name:String, id_body_part:Int) : com.lak.models.WeaponCategory
	{
		db.query('INSERT INTO `weapon_category`(`name`, `id_body_part`) VALUES (' + db.quote(name) + ', ' + db.quote(id_body_part) + ')');
		return newModelFromParams(db.lastInsertId(), name, id_body_part);
	}

	public function createNamed(data:{ name:String, id_body_part:Int }) : com.lak.models.WeaponCategory
	{
		db.query('INSERT INTO `weapon_category`(`name`, `id_body_part`) VALUES (' + db.quote(data.name) + ', ' + db.quote(data.id_body_part) + ')');
		return newModelFromParams(db.lastInsertId(), data.name, data.id_body_part);
	}

	public function createOptional(data:{ ?name:String, ?id_body_part:Int }) : com.lak.models.WeaponCategory
	{
		createOptionalNoReturn(data);
		return get(db.lastInsertId());
	}

	public function createOptionalNoReturn(data:{ ?name:String, ?id_body_part:Int }) : Void
	{
		var fields = [];
		var values = [];
		if (Reflect.hasField(data, 'name')) { fields.push('`name`'); values.push(db.quote(data.name)); }
		if (Reflect.hasField(data, 'id_body_part')) { fields.push('`id_body_part`'); values.push(db.quote(data.id_body_part)); }
		db.query('INSERT INTO `weapon_category`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `weapon_category` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.WeaponCategory>
	{
		return getBySqlMany('SELECT * FROM `weapon_category`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.WeaponCategory
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.WeaponCategory>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.WeaponCategory> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}
}