// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class WeaponStatsManager
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var query(get, never) : orm.SqlQuery<com.lak.models.WeaponStats>;

	function get_query() : orm.SqlQuery<com.lak.models.WeaponStats>
	{
		return new orm.SqlQuery<com.lak.models.WeaponStats>("weapon_stats", db, this);
	}

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	function newModelFromParams(id:Int, id_weapon:Int, value:String, id_weapon_stat_fields:Int) : com.lak.models.WeaponStats
	{
		var _obj = new com.lak.models.WeaponStats(db, orm);
		_obj.id = id;
		_obj.id_weapon = id_weapon;
		_obj.value = value;
		_obj.id_weapon_stat_fields = id_weapon_stat_fields;
		return _obj;
	}

	function newModelFromRow(d:Dynamic) : com.lak.models.WeaponStats
	{
		var _obj = new com.lak.models.WeaponStats(db, orm);
		_obj.id = Reflect.field(d, 'id');
		_obj.id_weapon = Reflect.field(d, 'id_weapon');
		_obj.value = Reflect.field(d, 'value');
		_obj.id_weapon_stat_fields = Reflect.field(d, 'id_weapon_stat_fields');
		return _obj;
	}

	public function where(field:String, op:String, value:Dynamic) : orm.SqlQuery<com.lak.models.WeaponStats>
	{
		return query.where(field, op, value);
	}

	public function get(id:Int) : com.lak.models.WeaponStats
	{
		return getBySqlOne('SELECT * FROM `weapon_stats` WHERE `id` = ' + db.quote(id));
	}

	public function create(id:Int, id_weapon:Int, value:String, id_weapon_stat_fields:Int) : com.lak.models.WeaponStats
	{
		db.query('INSERT INTO `weapon_stats`(`id`, `id_weapon`, `value`, `id_weapon_stat_fields`) VALUES (' + db.quote(id) + ', ' + db.quote(id_weapon) + ', ' + db.quote(value) + ', ' + db.quote(id_weapon_stat_fields) + ')');
		return newModelFromParams(id, id_weapon, value, id_weapon_stat_fields);
	}

	public function createNamed(data:{ id:Int, id_weapon:Int, value:String, id_weapon_stat_fields:Int }) : com.lak.models.WeaponStats
	{
		db.query('INSERT INTO `weapon_stats`(`id`, `id_weapon`, `value`, `id_weapon_stat_fields`) VALUES (' + db.quote(data.id) + ', ' + db.quote(data.id_weapon) + ', ' + db.quote(data.value) + ', ' + db.quote(data.id_weapon_stat_fields) + ')');
		return newModelFromParams(data.id, data.id_weapon, data.value, data.id_weapon_stat_fields);
	}

	public function createOptional(data:{ id:Int, ?id_weapon:Int, ?value:String, ?id_weapon_stat_fields:Int }) : com.lak.models.WeaponStats
	{
		createOptionalNoReturn(data);
		return get(data.id);
	}

	public function createOptionalNoReturn(data:{ id:Int, ?id_weapon:Int, ?value:String, ?id_weapon_stat_fields:Int }) : Void
	{
		var fields = [];
		var values = [];
		fields.push('`id`'); values.push(db.quote(data.id));
		if (Reflect.hasField(data, 'id_weapon')) { fields.push('`id_weapon`'); values.push(db.quote(data.id_weapon)); }
		if (Reflect.hasField(data, 'value')) { fields.push('`value`'); values.push(db.quote(data.value)); }
		if (Reflect.hasField(data, 'id_weapon_stat_fields')) { fields.push('`id_weapon_stat_fields`'); values.push(db.quote(data.id_weapon_stat_fields)); }
		db.query('INSERT INTO `weapon_stats`(' + fields.join(", ") + ') VALUES (' + values.join(", ") + ')');
	}

	public function delete(id:Int) : Void
	{
		db.query('DELETE FROM `weapon_stats` WHERE `id` = ' + db.quote(id) + ' LIMIT 1');
	}

	public function getAll(_order:String=null) : Array<com.lak.models.WeaponStats>
	{
		return getBySqlMany('SELECT * FROM `weapon_stats`' + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getBySqlOne(sql:String) : com.lak.models.WeaponStats
	{
		var rows = db.query(sql + ' LIMIT 1');
		if (rows.length == 0) return null;
		return newModelFromRow(rows.next());
	}

	public function getBySqlMany(sql:String) : Array<com.lak.models.WeaponStats>
	{
		var rows = db.query(sql);
		var list : Array<com.lak.models.WeaponStats> = [];
		for (row in rows)
		{
			list.push(newModelFromRow(row));
		}
		return list;
	}

	public function getById_weapon(id_weapon:Int, _order:String=null) : Array<com.lak.models.WeaponStats>
	{
		return getBySqlMany('SELECT * FROM `weapon_stats` WHERE `id_weapon` = ' + db.quote(id_weapon) + (_order != null ? ' ORDER BY ' + _order : ''));
	}

	public function getById_weapon_stat_fields(id_weapon_stat_fields:Int, _order:String=null) : Array<com.lak.models.WeaponStats>
	{
		return getBySqlMany('SELECT * FROM `weapon_stats` WHERE `id_weapon_stat_fields` = ' + db.quote(id_weapon_stat_fields) + (_order != null ? ' ORDER BY ' + _order : ''));
	}
}