// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class WeaponStats
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var id_weapon : Int;
	public var value : String;
	public var id_weapon_stat_fields : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(id_weapon:Int, value:String, id_weapon_stat_fields:Int) : Void
	{
		this.id_weapon = id_weapon;
		this.value = value;
		this.id_weapon_stat_fields = id_weapon_stat_fields;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `weapon_stats` SET '
				+  '`id_weapon` = ' + db.quote(id_weapon)
				+', `value` = ' + db.quote(value)
				+', `id_weapon_stat_fields` = ' + db.quote(id_weapon_stat_fields)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}