// This is autogenerated file. Do not edit!

package com.lak.models.autogenerated;

class Weapon
{
	var db : orm.Db;
	var orm : com.lak.models.Orm;
	public var id : Int;
	public var name : String;
	public var short_name : String;
	public var price : String;
	public var level : String;
	public var id_weapon_category : Int;
	public var id_weapon_type : Int;
	public var id_target_body_part : Int;

	public function new(db:orm.Db, orm:com.lak.models.Orm) : Void
	{
		this.db = db;
		this.orm = orm;
	}

	public function set(name:String, short_name:String, price:String, level:String, id_weapon_category:Int, id_weapon_type:Int, id_target_body_part:Int) : Void
	{
		this.name = name;
		this.short_name = short_name;
		this.price = price;
		this.level = level;
		this.id_weapon_category = id_weapon_category;
		this.id_weapon_type = id_weapon_type;
		this.id_target_body_part = id_target_body_part;
	}

	public function save() : Void
	{
		db.query(
			 'UPDATE `weapon` SET '
				+  '`name` = ' + db.quote(name)
				+', `short_name` = ' + db.quote(short_name)
				+', `price` = ' + db.quote(price)
				+', `level` = ' + db.quote(level)
				+', `id_weapon_category` = ' + db.quote(id_weapon_category)
				+', `id_weapon_type` = ' + db.quote(id_weapon_type)
				+', `id_target_body_part` = ' + db.quote(id_target_body_part)
			+' WHERE `id` = ' + db.quote(id)
			+' LIMIT 1'
		);
	}
}