-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 10:54:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lak_bdd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `lak_bdd` ;

-- -----------------------------------------------------
-- Schema lak_bdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lak_bdd` DEFAULT CHARACTER SET utf8 ;
USE `lak_bdd` ;

-- -----------------------------------------------------
-- Table `lak_bdd`.`units_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`units_type` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`units_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`mount_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`mount_category` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`mount_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`mount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`mount` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`mount` (
  `id` INT NOT NULL,
  `id_mount_category` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_mount_category_idx` (`id_mount_category` ASC),
  CONSTRAINT `fk_id_mount_category`
    FOREIGN KEY (`id_mount_category`)
    REFERENCES `lak_bdd`.`mount_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`civilization`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`civilization` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`civilization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `shortname` VARCHAR(45) NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`units` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_type` INT NULL,
  `id_mount` INT NULL,
  `id_civ` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_type_idx` (`id_type` ASC),
  INDEX `fk_id_mount_type_idx` (`id_mount` ASC),
  INDEX `fk_id_civ_idx` (`id_civ` ASC),
  CONSTRAINT `fk_id_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `lak_bdd`.`units_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_mount_type`
    FOREIGN KEY (`id_mount`)
    REFERENCES `lak_bdd`.`mount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_civ`
    FOREIGN KEY (`id_civ`)
    REFERENCES `lak_bdd`.`civilization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`body_parts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`body_parts` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`body_parts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`ressources_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`ressources_type` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`ressources_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`diplomacy_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`diplomacy_states` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`diplomacy_states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`strength`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`strength` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`strength` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `value` INT NULL,
  `id_stat_field` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`unit_stats_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`unit_stats_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`unit_stats_fields` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`unit_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`unit_stat` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`unit_stat` (
  `id` INT NOT NULL,
  `id_fields` INT NULL,
  `id_unit` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_unit_idx` (`id_unit` ASC),
  INDEX `fk_id_fields_idx` (`id_fields` ASC),
  CONSTRAINT `fk_id_unit`
    FOREIGN KEY (`id_unit`)
    REFERENCES `lak_bdd`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_fields`
    FOREIGN KEY (`id_fields`)
    REFERENCES `lak_bdd`.`unit_stats_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`mount_stat_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`mount_stat_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`mount_stat_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short` VARCHAR(45) NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`mount_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`mount_stat` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`mount_stat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_stat_field` INT NULL,
  `value` INT NULL,
  `id_mount` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_stat_field_idx` (`id_stat_field` ASC),
  INDEX `fk_id_mount_idx` (`id_mount` ASC),
  CONSTRAINT `fk_id_stat_field`
    FOREIGN KEY (`id_stat_field`)
    REFERENCES `lak_bdd`.`mount_stat_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_mount`
    FOREIGN KEY (`id_mount`)
    REFERENCES `lak_bdd`.`mount` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`weapon_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`weapon_category` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`weapon_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_body_part` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`weapon_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`weapon_type` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`weapon_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_category` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`weapon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`weapon` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`weapon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `level` VARCHAR(45) NULL,
  `id_weapon_category` INT NULL,
  `id_weapon_type` INT NULL,
  `id_target_body_part` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_weapon_category_idx` (`id_weapon_category` ASC),
  INDEX `fk_id_weapon_type_idx` (`id_weapon_type` ASC),
  INDEX `fk_id_target_body_part_idx` (`id_target_body_part` ASC),
  CONSTRAINT `fk_id_weapon_category`
    FOREIGN KEY (`id_weapon_category`)
    REFERENCES `lak_bdd`.`weapon_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_weapon_type`
    FOREIGN KEY (`id_weapon_type`)
    REFERENCES `lak_bdd`.`weapon_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_target_body_part`
    FOREIGN KEY (`id_target_body_part`)
    REFERENCES `lak_bdd`.`body_parts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`weapon_stat_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`weapon_stat_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`weapon_stat_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`weapon_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`weapon_stats` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`weapon_stats` (
  `id` INT NOT NULL,
  `id_weapon` INT NULL,
  `value` VARCHAR(45) NULL,
  `id_weapon_stat_fields` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_weapon_idx` (`id_weapon` ASC),
  INDEX `fk_id_weapon_stat_fields_idx` (`id_weapon_stat_fields` ASC),
  CONSTRAINT `fk_id_weapon`
    FOREIGN KEY (`id_weapon`)
    REFERENCES `lak_bdd`.`weapon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_weapon_stat_fields`
    FOREIGN KEY (`id_weapon_stat_fields`)
    REFERENCES `lak_bdd`.`weapon_stat_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`civilization_stat_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`civilization_stat_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`civilization_stat_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`civiization_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`civiization_stat` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`civiization_stat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_stat_fields` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_stat_fields_idx` (`id_stat_fields` ASC),
  CONSTRAINT `fk_id_stat_fields`
    FOREIGN KEY (`id_stat_fields`)
    REFERENCES `lak_bdd`.`civilization_stat_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`hero_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`hero_category` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`hero_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`heroes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`heroes` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`heroes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_civ` INT NULL,
  `id_hero_type` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_hero_type_idx` (`id_hero_type` ASC),
  INDEX `fk_id_civ_idx` (`id_civ` ASC),
  CONSTRAINT `fk_id_hero_type`
    FOREIGN KEY (`id_hero_type`)
    REFERENCES `lak_bdd`.`hero_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_hero_id_civ`
    FOREIGN KEY (`id_civ`)
    REFERENCES `lak_bdd`.`civilization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`heroes_stat_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`heroes_stat_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`heroes_stat_fields` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `short_name` VARCHAR(45) NULL,
  `id_heroe_skills` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`heroes_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`heroes_stat` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`heroes_stat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_heroes` INT NULL,
  `id_stat_fields` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_heroes_idx` (`id_heroes` ASC),
  INDEX `fk_id_stat_fields_idx` (`id_stat_fields` ASC),
  CONSTRAINT `fk_id_heroes`
    FOREIGN KEY (`id_heroes`)
    REFERENCES `lak_bdd`.`heroes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_heroes_id_stat_fields`
    FOREIGN KEY (`id_stat_fields`)
    REFERENCES `lak_bdd`.`heroes_stat_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`heroes_skills_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`heroes_skills_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`heroes_skills_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short` VARCHAR(45) NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`hero_skill_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`hero_skill_category` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`hero_skill_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `shortname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`hero_skills_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`hero_skills_stat` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`hero_skills_stat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_hero_skill_category` INT NULL,
  `id_hero` INT NULL,
  `value` VARCHAR(45) NULL,
  `id_heroe_skill_fields` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_hero_skill_category_idx` (`id_hero_skill_category` ASC),
  INDEX `fk_id_hero_idx` (`id_hero` ASC),
  INDEX `fk_id_heroe_skill_fields_idx` (`id_heroe_skill_fields` ASC),
  CONSTRAINT `fk_id_hero_skill_category`
    FOREIGN KEY (`id_hero_skill_category`)
    REFERENCES `lak_bdd`.`hero_skill_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_hero`
    FOREIGN KEY (`id_hero`)
    REFERENCES `lak_bdd`.`heroes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_heroe_skill_fields`
    FOREIGN KEY (`id_heroe_skill_fields`)
    REFERENCES `lak_bdd`.`heroes_skills_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`buildings_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`buildings_category` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`buildings_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `short` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`buildings` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`buildings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `shortname` VARCHAR(45) NULL,
  `id_building_category` INT NULL,
  `id_cost_category` INT NULL,
  `shape` TINYBLOB NULL,
  `offset` TINYBLOB NULL,
  `isProduction` TINYINT NULL DEFAULT 0,
  `canAttack` TINYINT NULL DEFAULT 0,
  `id_civ` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_building_category_idx` (`id_building_category` ASC),
  INDEX `fk_id_civ_idx` (`id_civ` ASC),
  CONSTRAINT `fk_id_building_category`
    FOREIGN KEY (`id_building_category`)
    REFERENCES `lak_bdd`.`buildings_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_building_id_civ`
    FOREIGN KEY (`id_civ`)
    REFERENCES `lak_bdd`.`civilization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`buildings_stat_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`buildings_stat_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`buildings_stat_fields` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`building_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`building_stats` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`building_stats` (
  `id` INT NOT NULL,
  `id_buildings_stat_fields` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_buildings_stat_fields_idx` (`id_buildings_stat_fields` ASC),
  CONSTRAINT `fk_id_buildings_stat_fields`
    FOREIGN KEY (`id_buildings_stat_fields`)
    REFERENCES `lak_bdd`.`buildings_stat_fields` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`research_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`research_category` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`research_category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`research`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`research` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`research` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_research_category` INT NULL,
  `id_target` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_research_category_idx` (`id_research_category` ASC),
  CONSTRAINT `fk_id_research_category`
    FOREIGN KEY (`id_research_category`)
    REFERENCES `lak_bdd`.`research_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`buildings_cost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`buildings_cost` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`buildings_cost` (
  `id` INT NOT NULL,
  `id_building` INT NULL,
  `id_ressource_type` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_ressource_type_idx` (`id_ressource_type` ASC),
  INDEX `fk_id_building_idx` (`id_building` ASC),
  CONSTRAINT `fk_id_ressource_type`
    FOREIGN KEY (`id_ressource_type`)
    REFERENCES `lak_bdd`.`ressources_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_building`
    FOREIGN KEY (`id_building`)
    REFERENCES `lak_bdd`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`building_research`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`building_research` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`building_research` (
  `id` INT NOT NULL,
  `id_building` INT NULL,
  `id_research` INT NULL,
  `finish` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_building_idx` (`id_building` ASC),
  INDEX `fk_id_research_idx` (`id_research` ASC),
  CONSTRAINT `fk_bresearch_id_building`
    FOREIGN KEY (`id_building`)
    REFERENCES `lak_bdd`.`buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bresearch_id_research`
    FOREIGN KEY (`id_research`)
    REFERENCES `lak_bdd`.`research` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`player` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`player` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `id_civ` INT NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_civ_idx` (`id_civ` ASC),
  CONSTRAINT `fk_player_id_civ`
    FOREIGN KEY (`id_civ`)
    REFERENCES `lak_bdd`.`civilization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`player_ressources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`player_ressources` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`player_ressources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_player` INT NULL,
  `id_ressource_type` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_ressource_type_idx` (`id_ressource_type` ASC),
  INDEX `fk_id_player_idx` (`id_player` ASC),
  CONSTRAINT `fk_ress_id_ressource_type`
    FOREIGN KEY (`id_ressource_type`)
    REFERENCES `lak_bdd`.`ressources_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ress_id_player`
    FOREIGN KEY (`id_player`)
    REFERENCES `lak_bdd`.`player` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`needs_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`needs_categories` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`needs_categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`research_needs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`research_needs` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`research_needs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_needs_category` INT NULL,
  `id_research` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_needs_category_idx` (`id_needs_category` ASC),
  INDEX `fk_id_research_idx` (`id_research` ASC),
  CONSTRAINT `fk_id_needs_category`
    FOREIGN KEY (`id_needs_category`)
    REFERENCES `lak_bdd`.`needs_categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_id_research`
    FOREIGN KEY (`id_research`)
    REFERENCES `lak_bdd`.`research` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`equipment` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`equipment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_player` INT NULL,
  `id_hero` INT NULL,
  `id_weapon` INT NULL,
  `id_body_part` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_hero_UNIQUE` (`id_hero` ASC),
  INDEX `fk_id_weapon_idx` (`id_weapon` ASC),
  INDEX `fk_id_body_part_idx` (`id_body_part` ASC),
  CONSTRAINT `fk_eq_id_hero`
    FOREIGN KEY (`id_hero`)
    REFERENCES `lak_bdd`.`heroes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eq_id_weapon`
    FOREIGN KEY (`id_weapon`)
    REFERENCES `lak_bdd`.`weapon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eq_id_body_part`
    FOREIGN KEY (`id_body_part`)
    REFERENCES `lak_bdd`.`body_parts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`morality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`morality` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`morality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_king` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_king_idx` (`id_king` ASC),
  CONSTRAINT `fk_id_king`
    FOREIGN KEY (`id_king`)
    REFERENCES `lak_bdd`.`heroes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`morality_stat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`morality_stat` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`morality_stat` (
  `id` INT NOT NULL,
  `id_morality` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_morality_field_idx` (`id_morality` ASC),
  CONSTRAINT `fk_id_morality_field`
    FOREIGN KEY (`id_morality`)
    REFERENCES `lak_bdd`.`morality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`morality_fields`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`morality_fields` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`morality_fields` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `id_morality_stat` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_morality_stat_idx` (`id_morality_stat` ASC),
  CONSTRAINT `fk_id_morality_stat`
    FOREIGN KEY (`id_morality_stat`)
    REFERENCES `lak_bdd`.`morality_stat` (`id_morality`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`units_cost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`units_cost` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`units_cost` (
  `id` INT NOT NULL,
  `id_units` INT NULL,
  `id_ressource_type` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_ressource_type_idx` (`id_ressource_type` ASC),
  INDEX `fk_id_units_idx` (`id_units` ASC),
  CONSTRAINT `fk_c_un_id_ressource_type`
    FOREIGN KEY (`id_ressource_type`)
    REFERENCES `lak_bdd`.`ressources_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_c_un_id_units`
    FOREIGN KEY (`id_units`)
    REFERENCES `lak_bdd`.`units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lak_bdd`.`research_cost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lak_bdd`.`research_cost` ;

CREATE TABLE IF NOT EXISTS `lak_bdd`.`research_cost` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_ressource_type` INT NULL,
  `id_research` INT NULL,
  `value` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_id_research_idx` (`id_research` ASC),
  INDEX `fk_id_ressource_type_idx` (`id_ressource_type` ASC),
  CONSTRAINT `fk_r_c_id_research`
    FOREIGN KEY (`id_research`)
    REFERENCES `lak_bdd`.`research` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_r_c_id_ressource_type`
    FOREIGN KEY (`id_ressource_type`)
    REFERENCES `lak_bdd`.`ressources_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
